services:
  postgres:
    image: postgres:17-alpine
    container_name: rps-postgres
    environment:
      POSTGRES_DB: rps
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rps"]
      interval: 5s
      timeout: 5s
      retries: 5
